### PR TITLE
feat: add an endpoint to get a user by ID

### PR DESCRIPTION
**Pull request by m0nd**

### CODE REVIEW

**Review by avendesta — CHANGES_REQUESTED** [review]
good that pipeline checks have passed. But you need to rebase it since other code has been pushed since your last push (use a save branch just in case), and add test cases to it.

**Comment by m0nd** [comment]
> good that pipeline checks have passed. But you need to rebase it since other code has been pushed since your last push (use a save branch just in case), and add test cases to it.

Ok cool. How do I rebase? I'm not too familiar

**Comment by avendesta** [comment]
let's meet and we can do it together.

**Comment by avendesta** [comment]
https://stackoverflow.com/questions/16666089/whats-the-difference-between-git-merge-and-git-rebase

**Review by avendesta — APPROVED** [review]

**Pull request merged**
